name: tag

on: [create]

jobs:
  main:
    runs-on: ubuntu-latest
    name: GoDoc
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
    - name: Generate GoDoc
      uses: ktr0731/godoc-action@v0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.vars.outputs.short_ref }}
